/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as DebugRouteRouteImport } from './routes/debug/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsTextProcessingRouteRouteImport } from './routes/settings/text-processing/route'
import { Route as SettingsStatsRouteRouteImport } from './routes/settings/stats/route'
import { Route as SettingsPersonasRouteRouteImport } from './routes/settings/personas/route'
import { Route as SettingsPermissionsRouteRouteImport } from './routes/settings/permissions/route'
import { Route as SettingsModelsRouteRouteImport } from './routes/settings/models/route'
import { Route as SettingsHistoryRouteRouteImport } from './routes/settings/history/route'
import { Route as SettingsGeneralRouteRouteImport } from './routes/settings/general/route'
import { Route as SettingsContentClassificationRouteRouteImport } from './routes/settings/content-classification/route'
import { Route as SettingsAudioRouteRouteImport } from './routes/settings/audio/route'
import { Route as SettingsAiEnhancementRouteRouteImport } from './routes/settings/ai-enhancement/route'
import { Route as SettingsAdvancedRouteRouteImport } from './routes/settings/advanced/route'
import { Route as DashboardInfoRouteRouteImport } from './routes/dashboard/info/route'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRouteRoute = DebugRouteRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTextProcessingRouteRoute =
  SettingsTextProcessingRouteRouteImport.update({
    id: '/text-processing',
    path: '/text-processing',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsStatsRouteRoute = SettingsStatsRouteRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPersonasRouteRoute = SettingsPersonasRouteRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPermissionsRouteRoute =
  SettingsPermissionsRouteRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsModelsRouteRoute = SettingsModelsRouteRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsHistoryRouteRoute = SettingsHistoryRouteRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsGeneralRouteRoute = SettingsGeneralRouteRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsContentClassificationRouteRoute =
  SettingsContentClassificationRouteRouteImport.update({
    id: '/content-classification',
    path: '/content-classification',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsAudioRouteRoute = SettingsAudioRouteRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAiEnhancementRouteRoute =
  SettingsAiEnhancementRouteRouteImport.update({
    id: '/ai-enhancement',
    path: '/ai-enhancement',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsAdvancedRouteRoute = SettingsAdvancedRouteRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const DashboardInfoRouteRoute = DashboardInfoRouteRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/debug': typeof DebugRouteRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/dashboard/info': typeof DashboardInfoRouteRoute
  '/settings/advanced': typeof SettingsAdvancedRouteRoute
  '/settings/ai-enhancement': typeof SettingsAiEnhancementRouteRoute
  '/settings/audio': typeof SettingsAudioRouteRoute
  '/settings/content-classification': typeof SettingsContentClassificationRouteRoute
  '/settings/general': typeof SettingsGeneralRouteRoute
  '/settings/history': typeof SettingsHistoryRouteRoute
  '/settings/models': typeof SettingsModelsRouteRoute
  '/settings/permissions': typeof SettingsPermissionsRouteRoute
  '/settings/personas': typeof SettingsPersonasRouteRoute
  '/settings/stats': typeof SettingsStatsRouteRoute
  '/settings/text-processing': typeof SettingsTextProcessingRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/debug': typeof DebugRouteRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/dashboard/info': typeof DashboardInfoRouteRoute
  '/settings/advanced': typeof SettingsAdvancedRouteRoute
  '/settings/ai-enhancement': typeof SettingsAiEnhancementRouteRoute
  '/settings/audio': typeof SettingsAudioRouteRoute
  '/settings/content-classification': typeof SettingsContentClassificationRouteRoute
  '/settings/general': typeof SettingsGeneralRouteRoute
  '/settings/history': typeof SettingsHistoryRouteRoute
  '/settings/models': typeof SettingsModelsRouteRoute
  '/settings/permissions': typeof SettingsPermissionsRouteRoute
  '/settings/personas': typeof SettingsPersonasRouteRoute
  '/settings/stats': typeof SettingsStatsRouteRoute
  '/settings/text-processing': typeof SettingsTextProcessingRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/debug': typeof DebugRouteRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/dashboard/info': typeof DashboardInfoRouteRoute
  '/settings/advanced': typeof SettingsAdvancedRouteRoute
  '/settings/ai-enhancement': typeof SettingsAiEnhancementRouteRoute
  '/settings/audio': typeof SettingsAudioRouteRoute
  '/settings/content-classification': typeof SettingsContentClassificationRouteRoute
  '/settings/general': typeof SettingsGeneralRouteRoute
  '/settings/history': typeof SettingsHistoryRouteRoute
  '/settings/models': typeof SettingsModelsRouteRoute
  '/settings/permissions': typeof SettingsPermissionsRouteRoute
  '/settings/personas': typeof SettingsPersonasRouteRoute
  '/settings/stats': typeof SettingsStatsRouteRoute
  '/settings/text-processing': typeof SettingsTextProcessingRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/debug'
    | '/settings'
    | '/dashboard/info'
    | '/settings/advanced'
    | '/settings/ai-enhancement'
    | '/settings/audio'
    | '/settings/content-classification'
    | '/settings/general'
    | '/settings/history'
    | '/settings/models'
    | '/settings/permissions'
    | '/settings/personas'
    | '/settings/stats'
    | '/settings/text-processing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/debug'
    | '/settings'
    | '/dashboard/info'
    | '/settings/advanced'
    | '/settings/ai-enhancement'
    | '/settings/audio'
    | '/settings/content-classification'
    | '/settings/general'
    | '/settings/history'
    | '/settings/models'
    | '/settings/permissions'
    | '/settings/personas'
    | '/settings/stats'
    | '/settings/text-processing'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/debug'
    | '/settings'
    | '/dashboard/info'
    | '/settings/advanced'
    | '/settings/ai-enhancement'
    | '/settings/audio'
    | '/settings/content-classification'
    | '/settings/general'
    | '/settings/history'
    | '/settings/models'
    | '/settings/permissions'
    | '/settings/personas'
    | '/settings/stats'
    | '/settings/text-processing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DebugRouteRoute: typeof DebugRouteRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/text-processing': {
      id: '/settings/text-processing'
      path: '/text-processing'
      fullPath: '/settings/text-processing'
      preLoaderRoute: typeof SettingsTextProcessingRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/stats': {
      id: '/settings/stats'
      path: '/stats'
      fullPath: '/settings/stats'
      preLoaderRoute: typeof SettingsStatsRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/personas': {
      id: '/settings/personas'
      path: '/personas'
      fullPath: '/settings/personas'
      preLoaderRoute: typeof SettingsPersonasRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/permissions': {
      id: '/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof SettingsPermissionsRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/history': {
      id: '/settings/history'
      path: '/history'
      fullPath: '/settings/history'
      preLoaderRoute: typeof SettingsHistoryRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/content-classification': {
      id: '/settings/content-classification'
      path: '/content-classification'
      fullPath: '/settings/content-classification'
      preLoaderRoute: typeof SettingsContentClassificationRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/audio': {
      id: '/settings/audio'
      path: '/audio'
      fullPath: '/settings/audio'
      preLoaderRoute: typeof SettingsAudioRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/ai-enhancement': {
      id: '/settings/ai-enhancement'
      path: '/ai-enhancement'
      fullPath: '/settings/ai-enhancement'
      preLoaderRoute: typeof SettingsAiEnhancementRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/dashboard/info': {
      id: '/dashboard/info'
      path: '/info'
      fullPath: '/dashboard/info'
      preLoaderRoute: typeof DashboardInfoRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardInfoRouteRoute: typeof DashboardInfoRouteRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardInfoRouteRoute: DashboardInfoRouteRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAdvancedRouteRoute: typeof SettingsAdvancedRouteRoute
  SettingsAiEnhancementRouteRoute: typeof SettingsAiEnhancementRouteRoute
  SettingsAudioRouteRoute: typeof SettingsAudioRouteRoute
  SettingsContentClassificationRouteRoute: typeof SettingsContentClassificationRouteRoute
  SettingsGeneralRouteRoute: typeof SettingsGeneralRouteRoute
  SettingsHistoryRouteRoute: typeof SettingsHistoryRouteRoute
  SettingsModelsRouteRoute: typeof SettingsModelsRouteRoute
  SettingsPermissionsRouteRoute: typeof SettingsPermissionsRouteRoute
  SettingsPersonasRouteRoute: typeof SettingsPersonasRouteRoute
  SettingsStatsRouteRoute: typeof SettingsStatsRouteRoute
  SettingsTextProcessingRouteRoute: typeof SettingsTextProcessingRouteRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAdvancedRouteRoute: SettingsAdvancedRouteRoute,
  SettingsAiEnhancementRouteRoute: SettingsAiEnhancementRouteRoute,
  SettingsAudioRouteRoute: SettingsAudioRouteRoute,
  SettingsContentClassificationRouteRoute:
    SettingsContentClassificationRouteRoute,
  SettingsGeneralRouteRoute: SettingsGeneralRouteRoute,
  SettingsHistoryRouteRoute: SettingsHistoryRouteRoute,
  SettingsModelsRouteRoute: SettingsModelsRouteRoute,
  SettingsPermissionsRouteRoute: SettingsPermissionsRouteRoute,
  SettingsPersonasRouteRoute: SettingsPersonasRouteRoute,
  SettingsStatsRouteRoute: SettingsStatsRouteRoute,
  SettingsTextProcessingRouteRoute: SettingsTextProcessingRouteRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DebugRouteRoute: DebugRouteRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
